CREATE TABLE IF NOT EXISTS devices (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    unique_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS positions (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	device_id INTEGER REFERENCES devices(id) ON DELETE CASCADE,
	latitude DOUBLE PRECISION NOT NULL,
	longitude DOUBLE PRECISION NOT NULL,
	fix_time TIMESTAMPTZ NOT NULL,
	server_time TIMESTAMPTZ NOT NULL,
	protocol TEXT NOT NULL,
	altitude DOUBLE PRECISION,
	speed DOUBLE PRECISION,
	course DOUBLE PRECISION,
	accuracy DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL
);
